# https://github.com/travis-ci/travis-ci/wiki/.travis.yml-options
bundler_args: --without development
script: "bundle exec rspec spec"
before_script: ./bin/ci/before_build.sh
rvm:
  - 1.8.7
  - 1.8.7-p249
  - ree
  - rbx-2.0
  - 1.9.2
  - jruby
gemfile:
  - Gemfile
  - gemfiles/eventmachine-pre
notifications:
  recipients:
    - jakub@rabbitmq.com
    - michaelklishin@me.com
    - markizko@gmail.com
