bundler_args: --without development
script: "bundle exec rspec spec"
before_script: ./bin/ci/before_build.sh
rvm:
  - 1.8.7
  - 1.8.7-p174
  - 1.8.7-p249
  - ree
  - rbx
  - 1.9.2
  - jruby
  - ruby-head
gemfile:
  - Gemfile
  - gemfiles/eventmachine-pre
